name: Destroy
description: Destroy the preview environment

inputs:
  environment:
    required: true
    description: The environment to destroy
  role:
    required: true
    description: IAM role to assume for deployment
  region:
    required: true
    description: AWS region to deploy to
  token:
    required: true
    description: GitHub token to use for deleting the environment
  neon_project:
    required: true
    description: Neon project name
  neon_token:
    required: true
    description: Neon API token

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: ${{ inputs.region }}

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - run: python -m venv .venv
      working-directory: deploy
      shell: bash

    - run: |
        source .venv/bin/activate
        python -m pip install -r requirements.txt
      working-directory: deploy
      shell: bash

    - run: |
        source .venv/bin/activate
        python unbranch.py
      working-directory: deploy
      shell: bash
      env:
        NEON_TOKEN: ${{ inputs.neon_token }}
        NEON_PROJECT: ${{ inputs.neon_project }}
        NEON_BRANCH: ${{ inputs.environment }}

    - run: |
        source .venv/bin/activate
        npx cdk destroy \
        --context environment=${{ inputs.environment }} \
        --context DATABASE_HOST=${{ steps.branch.outputs.db_host }} \
        --context DATABASE_DATABASE=${{ inputs.neon_database }} \
        --context DATABASE_USER=${{ steps.branch.outputs.db_user }} \
        --context DATABASE_PASSWORD=${{ steps.branch.outputs.db_password }} \
        --force
      working-directory: deploy
      shell: bash

    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          await github.rest.repos.deleteAnEnvironment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            environment_name: "${{ inputs.environment }}"
          });
