name: Destroy PR environment

on:
  pull_request:
    types:
      - closed

permissions:
  id-token: write
  deployments: write

jobs:
  pr-env-create:
    name: Destroy PR environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # CDK requires a file to construct the stack
      - run: touch lambda/neonbranch.zip

      - uses: ./.github/actions/destroy
        name: Destroy
        with:
          environment: pr-${{ github.event.number }}
          role: ${{ secrets.AWS_ROLE }}
          region: ${{ vars.AWS_REGION }}
