name: Synchronize PR environment

on:
  pull_request:
    types:
      - synchronize

permissions:
  id-token: write
  pull-requests: write

jobs:
  pr-env-sync:
    name: Synchronize PR environment
    runs-on: ubuntu-latest
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.URL }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build
        name: Build
        with:
          environment: pr-${{ github.event.number }}

      - id: deploy
        uses: ./.github/actions/deploy
        name: Deploy
        with:
          environment: pr-${{ github.event.number }}
          role: ${{ secrets.AWS_ROLE }}
          region: ${{ vars.AWS_REGION }}

      - uses: ./.github/actions/comment
        name: Comment
        with:
          URL: ${{ steps.deploy.outputs.URL }}
