name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.URL }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build
        name: Build

      - id: deploy
        uses: ./.github/actions/deploy
        name: Deploy
        with:
          role: ${{ secrets.AWS_ROLE }}
          region: ${{ vars.AWS_REGION }}
          neon_project: ${{ vars.NEON_PROJECT }}
          neon_database: ${{ vars.NEON_DATABASE }}
          neon_token: ${{ secrets.NEON_TOKEN }}
